/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'author' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ArticleInput {
  'title' : string,
  'content' : string,
  'author' : string,
  'excerpt' : string,
  'category' : string,
}
export interface Project {
  'title' : string,
  'featured' : boolean,
  'year' : bigint,
  'description' : string,
  'category' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addArticle' : ActorMethod<[ArticleInput], bigint>,
  'addProject' : ActorMethod<[Project], bigint>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getArticleById' : ActorMethod<[bigint], Article>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];