/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ArticleInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addArticle' : IDL.Func([ArticleInput], [IDL.Nat], []),
  'addProject' : IDL.Func([Project], [IDL.Nat], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ArticleInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addArticle' : IDL.Func([ArticleInput], [IDL.Nat], []),
    'addProject' : IDL.Func([Project], [IDL.Nat], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };